name: 'accessibility check'
on:
  pull_request:
    branches:
      - main
jobs:
  report:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: marianntapfer/a11y-report-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          storybook_url: 'somecustom.url'
