name: 'accessibility check'
on:
  pull_request:
    branches:
      - main
jobs:
  report:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          repository: marianntapfer/a11y-report-action
          token: ${{ secrets.A11Y_PAT }}
      - name: Run a11y-report-action
        uses: marianntapfer/a11y-report-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          storybook_url: 'somecustom.url'
