name: Test Label trigger

on:
  pull_request:
    types: [labeled]

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    # if: |
    #   contains(github.event.issue.labels.*.name, 'update-snapshots')
    steps:
      - run: |
          echo "This workflow was triggered"
          echo ${{ github.event.issue.labels.*.name[0] }}
          echo "${github.event.issue.labels.*.name}"
