name: Test Label trigger

on:
  pull_request:
    types: [labeled]

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug')
    steps:
      - run: echo "you added bug label"
