name: Update Snapshots

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  update-snapshots:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'update-snapshots')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-sb
      - name: Update snapshots
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook -- --updateSnapshot"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[CI] Updated Snapshots'
      - uses: actions-ecosystem/action-remove-labels@v1
        # if: ${{ startsWith(github.event.comment.body, '/remove-labels') }}
        with:
          labels: update-snapshots
