name: Testing scripts and PR comments
on:
  workflow_dispatch:
  pull_request:

jobs:
  log-the-input:
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |

            const commentTitle = 'Visual snapshot tests'
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }}
            })

            for (const comment of comments){
              if(comment.user?.login === 'github-actions[bot]' && comment.body?.includes(commentTitle)){
                github.rest.issues.deleteComment({
                  repo: context.repo.repo,
                  owner: context.repo.owner,
                  comment_id: comment.id 
                })
              }
            }

            console.log('Comments', comments)
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: `## ${commentTitle} \r\n See your test results here:`
            })

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
