name: Testing scripts and PR comments
on:
  workflow_dispatch:
    inputs:
      pet:
        description: 'Animal companion'
        required: true
        default: 'Dog'
        type: choice
        options:
          - 'Dog'
          - 'Cat'
          - 'Hamster'
  pull_request:

env:
  PET: ${{ inputs.pet }}
jobs:
  log-the-input:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        uses: actions/github-script@v6
        with:
          script: |
            const myPet = process.env.PET
            if (myPet === 'Dog') {
              console.log('Your dogs says Woof Woof!')
            } else if (myPet === 'Cat') {
              console.log('Your cat says Mjäu!')
            } else {
              console.log('I heard you have a pet. :)')
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
